substitutions:
  name: boneio-24-sw-07-737d50
  friendly_name: boneio-1
  serial_prefix: esp #Don't change it.

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: boneio.24x16-switches
    version: "0.7"

esp32:
  board: nodemcu-32s

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-24x16_switches_v0_7.yaml@latest
  import_full_config: true

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.6.0
    files:
      [
        devices/buzzer.yaml,
        devices/serial_no.yaml,
        devices_v0_7/display.yaml,
        devices_v0_7/i2c.yaml,
        devices_v0_7-v0_9/ina219.yaml,
        devices_v0_7-v0_9/lm75b.yaml,
        devices_v0_7-v0_9/pcf_with_mcp.yaml,
        devices_v0_7-v0_9/one_wire.yaml,
        boards/24x16_output.yaml,
      ]

logger:
api:
  reboot_timeout: 0s
ota:
  platform: esphome

web_server:
  port: 80
  local: true

time:
  - platform: homeassistant
    timezone: Europe/Warsaw
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    name: Switch 1-TR
    id: in_01
    pin:
      pcf8574: pcf_inputs_1to14
      number: 0
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 1-TL
    id: in_02
    pin:
      pcf8574: pcf_inputs_1to14
      number: 1
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 1-BR
    id: in_03
    pin:
      pcf8574: pcf_inputs_1to14
      number: 2
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 1-BL
    id: in_04
    pin:
      pcf8574: pcf_inputs_1to14
      number: 3
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.1-TL
    id: in_05
    pin:
      pcf8574: pcf_inputs_1to14
      number: 4
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.1-TR
    id: in_06
    pin:
      pcf8574: pcf_inputs_1to14
      number: 5
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.1-BL
    id: in_07
    pin:
      pcf8574: pcf_inputs_1to14
      number: 6
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.1-BR
    id: in_08
    pin:
      pcf8574: pcf_inputs_1to14
      number: 8
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.2-TL
    id: in_09
    pin:
      pcf8574: pcf_inputs_1to14
      number: 9
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.2-TR
    id: in_10
    pin:
      pcf8574: pcf_inputs_1to14
      number: 10
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.2-BL
    id: in_11
    pin:
      pcf8574: pcf_inputs_1to14
      number: 11
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.2-BR
    id: in_12
    pin:
      pcf8574: pcf_inputs_1to14
      number: 12
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 3-TR
    id: in_13
    pin:
      pcf8574: pcf_inputs_1to14
      number: 13
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 3-TL
    id: in_14
    pin:
      pcf8574: pcf_inputs_1to14
      number: 14
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 3-BR
    id: in_15
    pin:
      pcf8574: pcf_inputs_15to28
      number: 6
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 3-BL
    id: in_16
    pin:
      pcf8574: pcf_inputs_15to28
      number: 5
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 6-TL
    id: in_17
    pin:
      pcf8574: pcf_inputs_15to28
      number: 4
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 6-TR
    id: in_18
    pin:
      pcf8574: pcf_inputs_15to28
      number: 3
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 7.3-TL
    id: in_19
    pin:
      pcf8574: pcf_inputs_15to28
      number: 2
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 7.3-TR
    id: in_20
    pin:
      pcf8574: pcf_inputs_15to28
      number: 1
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_21
    id: in_21
    pin:
      pcf8574: pcf_inputs_15to28
      number: 0
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_22
    id: in_22
    pin:
      pcf8574: pcf_inputs_15to28
      number: 8
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 9.2-L
    id: in_23
    pin:
      pcf8574: pcf_inputs_15to28
      number: 9
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 9.2-R
    id: in_24
    pin:
      pcf8574: pcf_inputs_15to28
      number: 10
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 11.2-TL
    id: in_25
    pin:
      pcf8574: pcf_inputs_15to28
      number: 11
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 11.2-TR
    id: in_26
    pin:
      pcf8574: pcf_inputs_15to28
      number: 12
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 11.1-TL
    id: in_27
    pin:
      pcf8574: pcf_inputs_15to28
      number: 13
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 11.1-TR
    id: in_28
    pin:
      pcf8574: pcf_inputs_15to28
      number: 14
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 10.1-TL
    id: in_29
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 0
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 10.1-TR
    id: in_30
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 1
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: KT05 (pralnia)
    id: in_kt_05
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 2
      mode:
        input: true
      inverted: true
    # on_state:
    #   then:
    #     - if:
    #         condition:
    #           binary_sensor.is_on: in_kt_05
    #         then:
    #           - switch.turn_off:
    #               id: light_N
    #         else:
    #           - switch.turn_on:
    #               id: light_N

  - platform: gpio
    name: IN_32
    id: in_32
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 3
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_33
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 4
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_34
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 5
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_35
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 6
      mode:
        input: true
      inverted: true

sensor:
  - platform: dallas_temp
    address: 0x280723322814e928
    name: "Dallas Sensor 1"
    update_interval: 30s
    id: temp_mata

switch:
  - platform: output
    id: mata_grzewcza
    name: "Mata grzewcza"
    output: out_01

climate:
  - platform: thermostat
    name: "Mata grzewcza – termostat"
    sensor: temp_mata

    min_heating_off_time: 60s
    min_heating_run_time: 60s
    min_idle_time: 30s

    heat_deadband: 0.5
    heat_overrun: 0.5

    heat_action:
      - switch.turn_on: mata_grzewcza
    idle_action:
      - switch.turn_off: mata_grzewcza

    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 28
        mode: heat
      - name: Eco
        default_target_temperature_low: 26
######################
### MODBUS SECTION ###
######################
# UNCOMMENT BELOW TO USE MODBUS
# uart:
#   id: uart_pin14_15
#   rx_pin: GPIO14
#   tx_pin: GPIO15
#   baud_rate: 9600
#   stop_bits: 1

# modbus:
#   send_wait_time: 200ms
#   uart_id: uart_pin14_15
#   id: boneio_modbus

# modbus_controller:
#   - id: YOURDEVICE ID
#     address: 0x09
#     modbus_id: mod_bus
#     setup_priority: -10
#     update_interval: 60s
