substitutions:
  name: boneio-dr-8ch-03-4023d4
  friendly_name: BoneIO Dimmer LED 4023d4
  serial_prefix: dim #Don't change it.

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: boneio.dimmer-led
    version: "0.3"

esp32:
  board: esp32dev

external_components:
  - source: github://boneIO-eu/esphome-LM75@main #Original source and thank you note for BTomala https://github.com/boneIO-eu/esphome-lm75
    components: [lm75]

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.1.0
    files:
      [
        devices/serial_no.yaml,
        devices/dimmer_i2c.yaml,
        devices/dimmer_ina219.yaml,
      ]

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-dimmer_8ch-v0_3.yaml@latest
  import_full_config: true

pcf8574:
  - id: pcf_inputs
    address: 0x38

logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome

web_server:
  port: 80
  local: true

text_sensor:
  - platform: version
    name: boneio-dimmer- Version
    icon: mdi:cube-outline
    entity_category: diagnostic
  - platform: ethernet_info
    ip_address:
      entity_category: diagnostic
      name: boneio-dimmer IP
  - platform: template
    name: Hostname
    id: hostname
    entity_category: diagnostic
    lambda: |-
      return id(eth).get_use_address();
    update_interval: 5min

globals:
  - id: lastDirection_W
    type: bool
    restore_value: yes
    initial_value: "true"
  - id: lastDirection_U
    type: bool
    restore_value: yes
    initial_value: "true"
  - id: lastDirection_P
    type: bool
    restore_value: yes
    initial_value: "true"
  - id: lastDirection_T
    type: bool
    restore_value: yes
    initial_value: "true"
  - id: lastDirection_X
    type: bool
    restore_value: yes
    initial_value: "true"

binary_sensor:
  - platform: gpio
    id: in_01
    name: Switch 11.2-TL
    pin:
      pcf8574: pcf_inputs
      number: 1
      mode:
        input: true
      inverted: true
    on_click:
      then:
        - if:
            condition:
              - light.is_off: light_U
            then:
              - light.turn_on: light_U
        - if:
            condition:
              - light.is_on: light_U
            then:
              - light.turn_off: light_U
    on_press:
      then:
        - if:
            condition:
              or:
                - light.is_off: light_U
                - and:
                    - lambda: "return id(lastDirection_U) == true;"
                    - lambda: "return id(light_U).current_values.get_brightness() < 1;"
            then:
              - delay: 0.5s
              - while:
                  condition:
                    binary_sensor.is_on: in_01
                  then:
                    - lambda: "id(lastDirection_U) = false;"
                    - light.dim_relative:
                        id: light_U
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: in_01
                      - light.is_on: light_U
                      - lambda: "return id(light_U).current_values.get_brightness() > 0.2;"
                  then:
                    - lambda: "id(lastDirection_U) = true;"
                    - logger.log:
                        format: "Current brightness %.1f"
                        args: ["id(light_U).current_values.get_brightness()"]
                    - light.dim_relative:
                        id: light_U
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
  - platform: gpio
    id: in_02
    name: Switch 11.2-TR
    pin:
      pcf8574: pcf_inputs
      number: 2
      mode:
        input: true
      inverted: true
    on_click:
      then:
        - if:
            condition:
              - light.is_off: light_W
            then:
              - light.turn_on: light_W
        - if:
            condition:
              - light.is_on: light_W
            then:
              - light.turn_off: light_W
    on_press:
      then:
        - if:
            condition:
              or:
                - light.is_off: light_W
                - and:
                    - lambda: "return id(lastDirection_W) == true;"
                    - lambda: "return id(light_W).current_values.get_brightness() < 1;"
            then:
              - delay: 0.5s
              - while:
                  condition:
                    binary_sensor.is_on: in_02
                  then:
                    - lambda: "id(lastDirection_W) = false;"
                    - light.dim_relative:
                        id: light_W
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: in_02
                      - light.is_on: light_W
                      - lambda: "return id(light_W).current_values.get_brightness() > 0.2;"
                  then:
                    - lambda: "id(lastDirection_W) = true;"
                    - logger.log:
                        format: "Current brightness %.1f"
                        args: ["id(light_W).current_values.get_brightness()"]
                    - light.dim_relative:
                        id: light_W
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s

  - platform: gpio
    id: in_03
    name: Switch 11.1-TL
    pin:
      pcf8574: pcf_inputs
      number: 3
      mode:
        input: true
      inverted: true
    on_click:
      then:
        - if:
            condition:
              - light.is_off: light_P
            then:
              - light.turn_on: light_P
        - if:
            condition:
              - light.is_on: light_P
            then:
              - light.turn_off: light_P
    on_press:
      then:
        - if:
            condition:
              or:
                - light.is_off: light_P
                - and:
                    - lambda: "return id(lastDirection_P) == true;"
                    - lambda: "return id(light_P).current_values.get_brightness() < 1;"
            then:
              - delay: 0.5s
              - while:
                  condition:
                    binary_sensor.is_on: in_03
                  then:
                    - lambda: "id(lastDirection_P) = false;"
                    - light.dim_relative:
                        id: light_P
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: in_03
                      - light.is_on: light_P
                      - lambda: "return id(light_P).current_values.get_brightness() > 0.2;"
                  then:
                    - lambda: "id(lastDirection_P) = true;"
                    - logger.log:
                        format: "Current brightness %.1f"
                        args: ["id(light_P).current_values.get_brightness()"]
                    - light.dim_relative:
                        id: light_P
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s

  - platform: gpio
    name: Switch 10.1-TR
    id: in_04
    pin:
      pcf8574: pcf_inputs
      number: 4
      mode:
        input: true
      inverted: true
    on_click:
      then:
        - if:
            condition:
              - light.is_off: light_P
            then:
              - light.turn_on: light_P
        - if:
            condition:
              - light.is_on: light_P
            then:
              - light.turn_off: light_P
    on_press:
      then:
        - if:
            condition:
              or:
                - light.is_off: light_P
                - and:
                    - lambda: "return id(lastDirection_P) == true;"
                    - lambda: "return id(light_P).current_values.get_brightness() < 1;"
            then:
              - delay: 0.5s
              - while:
                  condition:
                    binary_sensor.is_on: in_04
                  then:
                    - lambda: "id(lastDirection_P) = false;"
                    - light.dim_relative:
                        id: light_P
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: in_04
                      - light.is_on: light_P
                      - lambda: "return id(light_P).current_values.get_brightness() > 0.2;"
                  then:
                    - lambda: "id(lastDirection_P) = true;"
                    - logger.log:
                        format: "Current brightness %.1f"
                        args: ["id(light_P).current_values.get_brightness()"]
                    - light.dim_relative:
                        id: light_P
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s

  - platform: gpio
    id: in_05
    name: Switch 11.2-TL
    pin:
      number: 36
      mode:
        input: true
      inverted: true
    on_click:
      then:
        - if:
            condition:
              - light.is_off: light_T
            then:
              - light.turn_on: light_T
        - if:
            condition:
              - light.is_on: light_T
            then:
              - light.turn_off: light_T
    on_press:
      then:
        - if:
            condition:
              or:
                - light.is_off: light_T
                - and:
                    - lambda: "return id(lastDirection_T) == true;"
                    - lambda: "return id(light_T).current_values.get_brightness() < 1;"
            then:
              - delay: 0.5s
              - while:
                  condition:
                    binary_sensor.is_on: in_05
                  then:
                    - lambda: "id(lastDirection_T) = false;"
                    - light.dim_relative:
                        id: light_T
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: in_05
                      - light.is_on: light_T
                      - lambda: "return id(light_T).current_values.get_brightness() > 0.2;"
                  then:
                    - lambda: "id(lastDirection_T) = true;"
                    - logger.log:
                        format: "Current brightness %.1f"
                        args: ["id(light_T).current_values.get_brightness()"]
                    - light.dim_relative:
                        id: light_T
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s

  - platform: gpio
    name: IN_06
    pin:
      number: 39
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: IN_07
    pin:
      number: 34
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: IN_08
    pin:
      number: 35
      mode:
        input: true
      inverted: true

output:
  - platform: ledc
    pin: 33
    frequency: 1000Hz
    inverted: false
    id: chl01
  - platform: ledc
    pin: 32
    frequency: 1000Hz
    inverted: false
    id: chl02
  - platform: ledc
    pin: 12
    frequency: 1000Hz
    inverted: false
    id: chl03
  - platform: ledc
    pin: 14
    frequency: 1000Hz
    inverted: false
    id: chl04

  - platform: ledc
    pin: 13
    frequency: 1000Hz
    inverted: false
    id: chr01
  - platform: ledc
    pin: 15
    frequency: 1000Hz
    inverted: false
    id: chr02
  - platform: ledc
    pin: 2
    frequency: 1000Hz
    inverted: false
    id: chr03
  - platform: ledc
    pin: 17
    frequency: 1000Hz
    inverted: false
    id: chr04

light:
  - platform: monochromatic
    output: chl01
    name: Light P (przejscie)
    id: light_P
    default_transition_length: 0.5s
    gamma_correct: 0
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: monochromatic
    output: chl02
    name: Light U (lodowka)
    id: light_U
    default_transition_length: 0.5s
    gamma_correct: 0
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: monochromatic
    output: chl03
    name: Light W (kuchenka)
    id: light_W
    default_transition_length: 0.5s
    gamma_correct: 0
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: monochromatic
    output: chl04
    name: CHL 04
    id: chl_04
    default_transition_length: 0.5s
    gamma_correct: 0
  - platform: monochromatic
    output: chr01
    name: CHR 01
    id: chr_01
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr02
    name: Light X (szafka)
    id: light_X
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr03
    name: Light T
    id: light_T
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr04
    name: CHR 04
    id: chr_04
    default_transition_length: 2s
    gamma_correct: 0

sensor:
  - platform: lm75
    id: boneIO_temp
    name: Temperature
    update_interval: 30s
    entity_category: diagnostic
    on_value_range:
      - above: 70.0
        then:
          - switch.turn_on: buzzer
      - below: 70.0
        then:
          - switch.turn_off: buzzer

switch:
  - platform: gpio
    id: buzzer
    name: Buzzer
    pin:
      pcf8574: pcf_inputs
      number: 0
      mode:
        output: true
      inverted: true
