substitutions:
  name: boneio-24-sw-07-737d50
  friendly_name: boneio-1
  serial_prefix: esp #Don't change it.

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: boneio.24x16-switches
    version: "0.7"

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-24x16_switches_v0_7.yaml@v1.7.1
  import_full_config: true

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.7.1
    files:
      [
        devices/buzzer.yaml,
        devices/serial_no.yaml,
        devices_v0_7/display.yaml,
        devices_v0_7/i2c.yaml,
        devices_v0_7-v0_9/ina219.yaml,
        devices_v0_7-v0_9/lm75b.yaml,
        devices_v0_7-v0_9/pcf_with_mcp.yaml,
        devices_v0_7-v0_9/one_wire.yaml,
        boards/24x16_output.yaml,
      ]
  sdm630:
    url: https://github.com/boneIO-eu/esphome_packages
    ref: 4c88a2ca9a76f9e483d5f79333ee5437395712b1
    files:
      - path: sdm630.yaml
        vars:
          device_name: "Licznik prądu - kuchenka"
          modbus_device_id: "sdm630"
          modbus_device_address: "0x01"
          modbus_id: "boneio_modbus"
          update_interval: "60s"
  sdm120_01:
    url: https://github.com/boneIO-eu/esphome_packages
    ref: 4c88a2ca9a76f9e483d5f79333ee5437395712b1
    files:
      - path: sdm120m.yaml
        vars:
          device_name: "Licznik prądu - piekarnik"
          modbus_device_id: "sdm120_01"
          modbus_device_address: "0x65"
          modbus_id: "boneio_modbus"
          update_interval: "60s"
  sdm120_02:
    url: https://github.com/boneIO-eu/esphome_packages
    ref: 4c88a2ca9a76f9e483d5f79333ee5437395712b1
    files:
      - path: sdm120m.yaml
        vars:
          device_name: "Licznik prądu - lodówka"
          modbus_device_id: "sdm120_02"
          modbus_device_address: "0x66"
          modbus_id: "boneio_modbus"
          update_interval: "60s"
  sdm120_03:
    url: https://github.com/boneIO-eu/esphome_packages
    ref: 4c88a2ca9a76f9e483d5f79333ee5437395712b1
    files:
      - path: sdm120m.yaml
        vars:
          device_name: "Licznik prądu - zmywarka"
          modbus_device_id: "sdm120_03"
          modbus_device_address: "0x67"
          modbus_id: "boneio_modbus"
          update_interval: "60s"
  sdm120_04:
    url: https://github.com/boneIO-eu/esphome_packages
    ref: 4c88a2ca9a76f9e483d5f79333ee5437395712b1
    files:
      - path: sdm120m.yaml
        vars:
          device_name: "Licznik prądu - klima salon"
          modbus_device_id: "sdm120_04"
          modbus_device_address: "0x68"
          modbus_id: "boneio_modbus"
          update_interval: "60s"
  sdm120_05:
    url: https://github.com/boneIO-eu/esphome_packages
    ref: 4c88a2ca9a76f9e483d5f79333ee5437395712b1
    files:
      - path: sdm120m.yaml
        vars:
          device_name: "Licznik prądu - oświetlenie"
          modbus_device_id: "sdm120_05"
          modbus_device_address: "0x69"
          modbus_id: "boneio_modbus"
          update_interval: "60s"
  sdm120_06:
    url: https://github.com/boneIO-eu/esphome_packages
    ref: 4c88a2ca9a76f9e483d5f79333ee5437395712b1
    files:
      - path: sdm120m.yaml
        vars:
          device_name: "Licznik prądu - pralka"
          modbus_device_id: "sdm120_06"
          modbus_device_address: "0x6a"
          modbus_id: "boneio_modbus"
          update_interval: "60s"
  sdm120_07:
    url: https://github.com/boneIO-eu/esphome_packages
    ref: 4c88a2ca9a76f9e483d5f79333ee5437395712b1
    files:
      - path: sdm120m.yaml
        vars:
          device_name: "Licznik prądu - suszarka"
          modbus_device_id: "sdm120_07"
          modbus_device_address: "0x6b"
          modbus_id: "boneio_modbus"
          update_interval: "60s"
  sdm120_08:
    url: https://github.com/boneIO-eu/esphome_packages
    ref: 4c88a2ca9a76f9e483d5f79333ee5437395712b1
    files:
      - path: sdm120m.yaml
        vars:
          device_name: "Licznik prądu - kompy"
          modbus_device_id: "sdm120_08"
          modbus_device_address: "0x6c"
          modbus_id: "boneio_modbus"
          update_interval: "60s"
  sdm120_09:
    url: https://github.com/boneIO-eu/esphome_packages
    ref: 4c88a2ca9a76f9e483d5f79333ee5437395712b1
    files:
      - path: sdm120m.yaml
        vars:
          device_name: "Licznik prądu - klima gabinet"
          modbus_device_id: "sdm120_09"
          modbus_device_address: "0x6d"
          modbus_id: "boneio_modbus"
          update_interval: "60s"
  sdm120_10:
    url: https://github.com/boneIO-eu/esphome_packages
    ref: 4c88a2ca9a76f9e483d5f79333ee5437395712b1
    files:
      - path: sdm120m.yaml
        vars:
          device_name: "Licznik prądu - RTV"
          modbus_device_id: "sdm120_10"
          modbus_device_address: "0x6e"
          modbus_id: "boneio_modbus"
          update_interval: "60s"

logger:
api:
  reboot_timeout: 0s
ota:
  platform: esphome

web_server:
  port: 80
  local: true

time:
  - platform: homeassistant
    timezone: Europe/Warsaw
    id: homeassistant_time

udp:

packet_transport:
  - platform: udp
    update_interval: 5s
    rolling_code_enable: true
    encryption: !secret boneio-1-enc_key
    binary_sensors:
      - bs_mata_on
    providers:
      - name: boneio-dr-8ch-03-4023d4
        encryption: !secret dimmer-5-enc_key

interval:
  - interval: 10s
    then:
      - lambda: |-
          auto on = id(mata_termostat).mode != CLIMATE_MODE_OFF;

          ESP_LOGD("thermostat-sync",
                   "Interval sync: heat=%s",
                   on ? "true" : "false");

          id(bs_mata_on).publish_state(on);

binary_sensor:
  - platform: gpio
    name: Switch 1-TR
    id: in_01
    pin:
      pcf8574: pcf_inputs_1to14
      number: 0
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 1-TL
    id: in_02
    pin:
      pcf8574: pcf_inputs_1to14
      number: 1
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 1-BR
    id: in_03
    pin:
      pcf8574: pcf_inputs_1to14
      number: 2
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 1-BL
    id: in_04
    pin:
      pcf8574: pcf_inputs_1to14
      number: 3
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.1-TL
    id: in_05
    pin:
      pcf8574: pcf_inputs_1to14
      number: 4
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.1-TR
    id: in_06
    pin:
      pcf8574: pcf_inputs_1to14
      number: 5
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.1-BL
    id: in_07
    pin:
      pcf8574: pcf_inputs_1to14
      number: 6
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.1-BR
    id: in_08
    pin:
      pcf8574: pcf_inputs_1to14
      number: 8
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.2-TL
    id: in_09
    pin:
      pcf8574: pcf_inputs_1to14
      number: 9
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.2-TR
    id: in_10
    pin:
      pcf8574: pcf_inputs_1to14
      number: 10
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.2-BL
    id: in_11
    pin:
      pcf8574: pcf_inputs_1to14
      number: 11
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 2.2-BR
    id: in_12
    pin:
      pcf8574: pcf_inputs_1to14
      number: 12
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 3-TR
    id: in_13
    pin:
      pcf8574: pcf_inputs_1to14
      number: 13
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 3-TL
    id: in_14
    pin:
      pcf8574: pcf_inputs_1to14
      number: 14
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 3-BR
    id: in_15
    pin:
      pcf8574: pcf_inputs_15to28
      number: 6
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 3-BL
    id: in_16
    pin:
      pcf8574: pcf_inputs_15to28
      number: 5
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 6-TL
    id: in_17
    pin:
      pcf8574: pcf_inputs_15to28
      number: 4
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 6-TR
    id: in_18
    pin:
      pcf8574: pcf_inputs_15to28
      number: 3
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 7.3-TL
    id: in_19
    pin:
      pcf8574: pcf_inputs_15to28
      number: 2
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 7.3-TR
    id: in_20
    pin:
      pcf8574: pcf_inputs_15to28
      number: 1
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_21
    id: in_21
    pin:
      pcf8574: pcf_inputs_15to28
      number: 0
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_22
    id: in_22
    pin:
      pcf8574: pcf_inputs_15to28
      number: 8
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 9.2-L
    id: in_23
    pin:
      pcf8574: pcf_inputs_15to28
      number: 9
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 9.2-R
    id: in_24
    pin:
      pcf8574: pcf_inputs_15to28
      number: 10
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 11.2-TL
    id: in_25
    pin:
      pcf8574: pcf_inputs_15to28
      number: 11
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 11.2-TR
    id: in_26
    pin:
      pcf8574: pcf_inputs_15to28
      number: 12
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 11.1-TL
    id: in_27
    pin:
      pcf8574: pcf_inputs_15to28
      number: 13
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 11.1-TR
    id: in_28
    pin:
      pcf8574: pcf_inputs_15to28
      number: 14
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 10.1-TL
    id: in_29
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 0
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: Switch 10.1-TR
    id: in_30
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 1
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: KT05 (pralnia)
    id: in_kt_05
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 2
      mode:
        input: true
      inverted: true
    # on_state:
    #   then:
    #     - if:
    #         condition:
    #           binary_sensor.is_on: in_kt_05
    #         then:
    #           - switch.turn_off:
    #               id: light_N
    #         else:
    #           - switch.turn_on:
    #               id: light_N

  - platform: gpio
    name: IN_32
    id: in_32
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 3
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_33
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 4
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_34
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 5
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_35
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 6
      mode:
        input: true
      inverted: true

  - platform: packet_transport
    provider: boneio-dr-8ch-03-4023d4
    id: r5_in_08
    remote_id: in_08
    on_click:
      then:
        - if:
            condition:
              lambda: |-
                return id(mata_termostat).mode != climate::CLIMATE_MODE_OFF;
            then:
              - climate.control:
                  id: mata_termostat
                  mode: "OFF"
            else:
              - climate.control:
                  id: mata_termostat
                  mode: "HEAT"

  - platform: template
    id: bs_mata_on
    name: "Mata ON (remote)"
    internal: true

sensor:
  - platform: dallas_temp
    address: 0x280723322814e928
    name: "Dallas Sensor 1"
    update_interval: 30s
    id: temp_mata

switch:
  - platform: output
    id: mata_grzewcza
    name: "Mata grzewcza"
    output: out_01

climate:
  - platform: thermostat
    id: mata_termostat
    name: "Mata grzewcza – termostat"
    sensor: temp_mata

    min_heating_off_time: 60s
    min_heating_run_time: 60s
    min_idle_time: 30s

    heat_deadband: 0.5
    heat_overrun: 0.5

    heat_action:
      - switch.turn_on: mata_grzewcza
    idle_action:
      - switch.turn_off: mata_grzewcza

    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 28
        mode: heat
      - name: Eco
        default_target_temperature_low: 26
    on_control:
      - logger.log: "Control input received; configuration updated!"
      - lambda: |-
          id(bs_mata_on).publish_state(
            x.get_mode() != CLIMATE_MODE_OFF
          );
######################
### MODBUS SECTION ###
######################
# UNCOMMENT BELOW TO USE MODBUS
uart:
  id: uart_pin14_15
  rx_pin: GPIO14
  tx_pin: GPIO15
  baud_rate: 9600
  stop_bits: 1

modbus:
  send_wait_time: 200ms
  uart_id: uart_pin14_15
  id: boneio_modbus
# modbus_controller:
#   - id: YOURDEVICE ID
#     address: 0x09
#     modbus_id: mod_bus
#     setup_priority: -10
#     update_interval: 60s
