substitutions:
  name: boneio-dr-8ch-03-32ce68
  friendly_name: dimmer-1-hall
  serial_prefix: dim #Don't change it.

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: boneio.dimmer-led
    version: "0.3"

esp32:
  board: esp32dev

external_components:
  - source: github://boneIO-eu/esphome-LM75@main #Original source and thank you note for BTomala https://github.com/boneIO-eu/esphome-lm75
    components: [lm75]

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.5.0
    files:
      [
        devices/serial_no.yaml,
        devices/dimmer_i2c.yaml,
        devices/dimmer_ina219.yaml,
        boards/dimmer_output.yaml,
      ]

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-dimmer_8ch-v0_3.yaml@latest
  import_full_config: true

pcf8574:
  - id: pcf_inputs
    address: 0x38

logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome

# udp:
#   update_interval: 5s
#   encryption: !secret dimmer-1-enc_key #set it to yours shared secret key
#   rolling_code_enable: true
#   binary_sensors:
#     - in_01

web_server:
  port: 80
  local: true

text_sensor:
  - platform: version
    name: boneio-dimmer- Version
    icon: mdi:cube-outline
    entity_category: diagnostic
  - platform: ethernet_info
    ip_address:
      entity_category: diagnostic
      name: boneio-dimmer IP
  - platform: template
    name: Hostname
    id: hostname
    entity_category: diagnostic
    lambda: |-
      return id(eth).get_use_address();
    update_interval: 5min

binary_sensor:
  - platform: gpio
    name: 1_1_433
    id: in_01
    pin:
      pcf8574: pcf_inputs
      number: 1
      mode:
        input: true
      inverted: true
    on_click:
      then:
        - if:
            condition:
              - light.is_off: light_b2
            then:
              - light.turn_on: light_b2
            else:
              - if:
                  condition:
                    - light.is_on: light_b2
                  then:
                    - light.turn_off: light_b2
    on_press:
      - while:
          condition:
            binary_sensor.is_on: in_01
          then:
            - light.dim_relative:
                id: light_b2
                relative_brightness: 5%
                transition_length: 0.1s
                brightness_limits:
                  max_brightness: 90%
            - delay: 0.1s

  - platform: gpio
    name: 1_1_434
    id: in_02
    pin:
      pcf8574: pcf_inputs
      number: 2
      mode:
        input: true
      inverted: true
    on_click:
      then:
        - if:
            condition:
              - light.is_off: light_a
            then:
              - light.turn_on: light_a
        - if:
            condition:
              - light.is_on: light_a
            then:
              - light.turn_off: light_a
    on_press:
      - while:
          condition:
            binary_sensor.is_on: in_01
          then:
            - light.dim_relative:
                id: light_a
                relative_brightness: 5%
                transition_length: 0.1s
                brightness_limits:
                  max_brightness: 90%
            - delay: 0.1s

  - platform: gpio
    name: 1_1_437
    id: in_03
    pin:
      pcf8574: pcf_inputs
      number: 3
      mode:
        input: true
      inverted: true
    on_click:
      then:
        - if:
            condition:
              - light.is_off: light_b1
            then:
              - light.turn_on: light_b1
        - if:
            condition:
              - light.is_on: light_b1
            then:
              - light.turn_off: light_b1
    on_press:
      - while:
          condition:
            binary_sensor.is_on: in_01
          then:
            - light.dim_relative:
                id: light_b1
                relative_brightness: 5%
                transition_length: 0.1s
                brightness_limits:
                  max_brightness: 90%
            - delay: 0.1s

  - platform: gpio
    name: 1_1_438
    id: in_04
    pin:
      pcf8574: pcf_inputs
      number: 4
      mode:
        input: true
      inverted: true
    on_click:
      then:
        - if:
            condition:
              - light.is_off: light_d
            then:
              - light.turn_on: light_d
        - if:
            condition:
              - light.is_on: light_d
            then:
              - light.turn_off: light_d
    on_press:
      - while:
          condition:
            binary_sensor.is_on: in_01
          then:
            - light.dim_relative:
                id: light_d
                relative_brightness: 5%
                transition_length: 0.1s
                brightness_limits:
                  max_brightness: 90%
            - delay: 0.1s

  - platform: gpio
    name: 12_1_353
    id: in_05
    pin:
      number: 36
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: 12_1_354
    id: in_06
    pin:
      number: 39
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: 12_1_357
    id: in_07
    pin:
      number: 34
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: 12_1_358
    id: in_08
    pin:
      number: 35
      mode:
        input: true
      inverted: true

light:
  - platform: cwww
    id: light_a
    name: light_a
    cold_white: chl01
    warm_white: chl02
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2000 K
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: cwww
    id: light_b1
    name: light_b1
    cold_white: chl03
    warm_white: chl04
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2000 K
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: cwww
    id: light_b2
    name: light_b2
    cold_white: chr01
    warm_white: chr02
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2000 K
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: cwww
    id: light_d
    name: light_d
    cold_white: chr03
    warm_white: chr04
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2000 K
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: lm75
    id: boneIO_temp
    name: Temperature
    update_interval: 30s
    entity_category: diagnostic
    on_value_range:
      - above: 70.0
        then:
          - switch.turn_on: buzzer
      - below: 70.0
        then:
          - switch.turn_off: buzzer

switch:
  - platform: gpio
    id: buzzer
    name: Buzzer
    pin:
      pcf8574: pcf_inputs
      number: 0
      mode:
        output: true
      inverted: true
